# Generated by Django 4.2.20 on 2025-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenresonancia',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
