# Generated by Django 3.2.6 on 2025-03-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_medicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenresonancia',
            name='medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagenresonancia',
            name='paciente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagenresonancia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
