# Generated by Django 4.2.20 on 2025-04-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_medicos', '0002_imagenresonancia_diagnostico'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenresonancia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagenresonancia',
            name='diagnostico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos_medicos.diagnosticomri'),
        ),
    ]
