# Generated by Django 5.1.7 on 2025-03-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_medicos', '0002_auto_20250313_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenresonancia',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
