# Generated by Django 5.1.7 on 2025-03-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_medicos', '0003_alter_imagenresonancia_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoMRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=255)),
                ('paciente', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='resonancias/')),
                ('analisis', models.TextField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos_medicos.examen')),
            ],
        ),
    ]
