# Generated by Django 5.2 on 2025-05-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_medico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
